from abc import ABC, abstractmethod
from typing import AsyncGenerator, Dict, List, Any, Optional


class ILLMClient(ABC):
    """Interface for connecting to external Language Models."""

    @abstractmethod
    async def generate_response(
        self, messages: List[Dict[str, Any]], temperature: Optional[float] = None, max_tokens: Optional[int] = None
    ) -> str:
        """
        Generate a complete synchronous text response based on injected messages.
        `messages` should adhere to typical [{"role": "user", "content": "..."}] structure.
        """
        pass

    @abstractmethod
    async def stream_response(
        self, messages: List[Dict[str, Any]], temperature: Optional[float] = None, max_tokens: Optional[int] = None
    ) -> AsyncGenerator[str, None]:
        """
        Stream back pieces of text as they are generated by the underlying model.
        """
        yield ""
