"""Add AI config fields to system_settings

Revision ID: 0dea3fb59b25
Revises: 9c40cd30091a
Create Date: 2026-06-17 21:40:39.171236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dea3fb59b25'
down_revision: Union[str, Sequence[str], None] = '9c40cd30091a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('ai_model_name', sa.String(length=50), nullable=False, server_default='gpt-4o-mini'))
    op.add_column('system_settings', sa.Column('ai_temperature', sa.Float(), nullable=False, server_default='0.2'))
    op.add_column('system_settings', sa.Column('ai_max_tokens', sa.Integer(), nullable=False, server_default='1200'))
    op.add_column('system_settings', sa.Column('ai_top_p', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('system_settings', sa.Column('ai_frequency_penalty', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'ai_frequency_penalty')
    op.drop_column('system_settings', 'ai_top_p')
    op.drop_column('system_settings', 'ai_max_tokens')
    op.drop_column('system_settings', 'ai_temperature')
    op.drop_column('system_settings', 'ai_model_name')
    # ### end Alembic commands ###
