"""drop translation_logs

Revision ID: 17b6ba214bca
Revises: a54c3e16ea69
Create Date: 2026-07-07 20:43:17.668796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b6ba214bca'
down_revision: Union[str, Sequence[str], None] = 'a54c3e16ea69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_logs_user_id'), table_name='translation_logs')
    op.drop_table('translation_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('translation_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('translation_logs_pkey'))
    )
    op.create_index(op.f('ix_translation_logs_user_id'), 'translation_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
