"""add semantic_caches table

Revision ID: 409bf7eef5f7
Revises: d3aa0a1112f2
Create Date: 2026-05-01 10:40:25.792326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '409bf7eef5f7'
down_revision: Union[str, Sequence[str], None] = 'd3aa0a1112f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_caches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.Column('response_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semantic_caches')
    # ### end Alembic commands ###
