"""Add characters_generated to audio_requests

Revision ID: 4b4ed0d862a6
Revises: 5e5cabcc7c51
Create Date: 2026-06-06 13:14:25.127168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4ed0d862a6'
down_revision: Union[str, Sequence[str], None] = '5e5cabcc7c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_requests', sa.Column('characters_generated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_requests', 'characters_generated')
    # ### end Alembic commands ###
