"""Add collection_id

Revision ID: 57fa35b598a6
Revises: f3203f246357
Create Date: 2026-06-27 12:52:56.462636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fa35b598a6'
down_revision: Union[str, Sequence[str], None] = 'f3203f246357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('collection_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'collection_id')
    # ### end Alembic commands ###
