"""Add retrieval latency to RetrievalLog

Revision ID: 64255ae3dcaf
Revises: 57fa35b598a6
Create Date: 2026-06-29 13:55:30.403770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64255ae3dcaf'
down_revision: Union[str, Sequence[str], None] = '57fa35b598a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retrieval_logs', sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retrieval_logs', 'retrieval_latency_ms')
    # ### end Alembic commands ###
