"""Add archived and pinned to conversation

Revision ID: 658609fa40ff
Revises: 7a709eb881a8
Create Date: 2026-05-07 22:28:35.755175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658609fa40ff'
down_revision: Union[str, Sequence[str], None] = '7a709eb881a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_pinned')
    op.drop_column('conversations', 'is_archived')
    # ### end Alembic commands ###
