"""add query context to llm request

Revision ID: 6b0961318960
Revises: 525254c81e40
Create Date: 2026-06-06 21:11:54.004677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0961318960'
down_revision: Union[str, Sequence[str], None] = '525254c81e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_requests', sa.Column('query', sa.Text(), nullable=True))
    op.add_column('llm_requests', sa.Column('context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_requests', 'context')
    op.drop_column('llm_requests', 'query')
    # ### end Alembic commands ###
