"""Add SecurityEvent model

Revision ID: 7a3ae93f1250
Revises: acd98e5ab3fc
Create Date: 2026-06-06 15:34:55.050952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3ae93f1250'
down_revision: Union[str, Sequence[str], None] = 'acd98e5ab3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_events_area', 'security_events', ['area'], unique=False)
    op.create_index('idx_security_events_created', 'security_events', ['created_at'], unique=False)
    op.create_index('idx_security_events_severity', 'security_events', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_security_events_severity', table_name='security_events')
    op.drop_index('idx_security_events_created', table_name='security_events')
    op.drop_index('idx_security_events_area', table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
