"""update conversation_id type

Revision ID: 875856dfd03a
Revises: 8f5cffb81277
Create Date: 2026-05-01 12:01:46.209734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875856dfd03a'
down_revision: Union[str, Sequence[str], None] = '8f5cffb81277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retrieval_logs', 'conversation_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="conversation_id::text::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retrieval_logs', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
