"""remove translation table

Revision ID: 8f5cffb81277
Revises: 409bf7eef5f7
Create Date: 2026-05-01 11:45:34.241235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f5cffb81277'
down_revision: Union[str, Sequence[str], None] = '409bf7eef5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('translated_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('translations_pkey'))
    )
    # ### end Alembic commands ###
