"""Add system_settings

Revision ID: 9c40cd30091a
Revises: 6b0961318960
Create Date: 2026-06-17 20:19:23.247230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c40cd30091a'
down_revision: Union[str, Sequence[str], None] = '6b0961318960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enabled_languages', sa.JSON(), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('translation_pipeline_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
