"""Add RetrievalEvaluation model

Revision ID: 9de042dd1981
Revises: 7a3ae93f1250
Create Date: 2026-06-06 16:39:02.773874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de042dd1981'
down_revision: Union[str, Sequence[str], None] = '7a3ae93f1250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recall_at_5', sa.Float(), nullable=False),
    sa.Column('precision_at_5', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retrieval_evaluations')
    # ### end Alembic commands ###
