"""Add security settings and user lockout

Revision ID: a54c3e16ea69
Revises: 4b7fe366cf41
Create Date: 2026-07-04 17:28:56.637918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54c3e16ea69'
down_revision: Union[str, Sequence[str], None] = '4b7fe366cf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('jwt_expiry_minutes', sa.Integer(), nullable=False, server_default='60'))
    op.add_column('system_settings', sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('system_settings', sa.Column('prompt_validation_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('system_settings', sa.Column('account_lockout_threshold', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('system_settings', 'account_lockout_threshold')
    op.drop_column('system_settings', 'prompt_validation_enabled')
    op.drop_column('system_settings', 'rate_limit_per_minute')
    op.drop_column('system_settings', 'jwt_expiry_minutes')
    # ### end Alembic commands ###
