"""Add retrieval config fields to system_settings

Revision ID: ad0f704cbdc1
Revises: 0dea3fb59b25
Create Date: 2026-06-17 22:17:01.402137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0f704cbdc1'
down_revision: Union[str, Sequence[str], None] = '0dea3fb59b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('retrieval_top_k', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('system_settings', sa.Column('retrieval_similarity_threshold', sa.Float(), nullable=False, server_default='0.7'))
    op.add_column('system_settings', sa.Column('retrieval_embedding_model', sa.String(length=50), nullable=False, server_default='text-embedding-3-large'))
    op.add_column('system_settings', sa.Column('retrieval_chunk_size', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('system_settings', sa.Column('retrieval_chunk_overlap', sa.Integer(), nullable=False, server_default='200'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'retrieval_chunk_overlap')
    op.drop_column('system_settings', 'retrieval_chunk_size')
    op.drop_column('system_settings', 'retrieval_embedding_model')
    op.drop_column('system_settings', 'retrieval_similarity_threshold')
    op.drop_column('system_settings', 'retrieval_top_k')
    # ### end Alembic commands ###
