"""Add integration settings fields

Revision ID: f3203f246357
Revises: ad0f704cbdc1
Create Date: 2026-06-17 23:01:49.839180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3203f246357'
down_revision: Union[str, Sequence[str], None] = 'ad0f704cbdc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('twilio_account_sid', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('twilio_auth_token', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('whatsapp_phone_number', sa.String(length=50), nullable=True))
    op.add_column('system_settings', sa.Column('web_socket_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'web_socket_url')
    op.drop_column('system_settings', 'whatsapp_phone_number')
    op.drop_column('system_settings', 'twilio_auth_token')
    op.drop_column('system_settings', 'twilio_account_sid')
    op.drop_column('system_settings', 'openai_api_key')
    # ### end Alembic commands ###
